<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotToursManager.Models\HotToursManager.Models.csproj" />
    <ProjectReference Include="..\HotToursManager.Services.Contracts\HotToursManager.Services.Contracts.csproj" />
    <ProjectReference Include="..\HotToursManager.Services\HotToursManager.Services.csproj" />
    <ProjectReference Include="..\HotToursManager.Storage.Contracts\HotToursManager.Storage.Contracts.csproj" />
    <ProjectReference Include="..\HotToursManager.Storage.DataBase\HotToursManager.Storage.DataBase.csproj" />
  </ItemGroup>

</Project>
